id: IAAFA6F08
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T21:52:51+00:00'
last_modified: '2022-06-15T18:05:46.020171+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74360
  title: འཁོར་ལོ་སྡོམ་པའི་མངོན་རྟོགས་ནག་འགྲོས་སུ་བཀོད་པ་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F0FD:
      image_group_id: I4CZ74362
      title: Volume 1 of 'khor lo sdom pa'i mngon rtogs nag 'gros su bkod pa/
      total_pages: 166
      order: 1
      base_file: F0FD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
